config/routes.rb
Rails.application.routes.draw do
  root 'beverages#index'

  get 'beverages/index'
  get 'beverages/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beverage.rb
class Beverage
  PUNK_API_BASE_URL = 'https://api.punkapi.com/v2/'.freeze
  PER_PAGE = 10

  def initialize(params:)
    @params = params
  end

  def sought_beer
    return if id.blank?

    response = Faraday.get(sought_beer_url)
    return if response.status != 200

    JSON.parse(response.body).first
  end

  def sought_beers
    return if query.blank?

    response = Faraday.get(sought_beers_url)
    return if response.status != 200

    JSON.parse(response.body)
  end

  private

  attr_reader :params

  def sought_beer_url
    "#{PUNK_API_BASE_URL}beers/#{id}"
  end

  def sought_beers_url
    "#{PUNK_API_BASE_URL}beers?beer_name=#{query}&page=#{page}&per_page=#{PER_PAGE}"
  end

  def id
    params[:id]
  end

  def query
    params[:query]
  end

  def page
    params[:page] || 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  def index
    @beers = Beverage.new(params: permitted_params).sought_beers
  end

  def show
    @beer = Beverage.new(params: permitted_params).sought_beer
  end

  def permitted_params
    params.permit(:id, :query, :page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/views/beverages/index.haml
:ruby
  page = params[:page] || 1

.c-beverages
  .c-beverages__search
    = form_with url: beverages_index_path, method: :get do |form|
      = form.text_field :query
      = form.submit 'Search'

  - if params[:query].blank?
    .c-beverages__blank-query
      %p Enter your search query
  - elsif @beers.blank?
    .c-beverages__no-results
      %p No beers found
      %br

      = link_to 'Previous', beverages_index_path(query: params[:query], page: page.to_i - 1) if page.to_i > 1
  - else
    .c-beverages__beers
      - @beers.each do |beer|
        = link_to "#{beer['name']}, #{beer['abv']}%", beverages_show_path(id: beer['id'])
        %br

      %br
      %br
      = link_to 'Previous', beverages_index_path(query: params[:query], page: page.to_i - 1) if page.to_i > 1
      = link_to 'Next', beverages_index_path(query: params[:query], page: page.to_i + 1) if @beers.size == 10

app/views/beverages/show.haml
.c-beverage
  .c-beverage__image
    = image_tag @beer['image_url'], height: '90%'

  .c-beverage__name
    = "#{@beer['name']}, #{@beer['abv']}%"

  .c-beverage__description
    = @beer['description']

  .c-beverage__food-pairing
    %p Food pairing:
    - @beer['food_pairing'].each do |food|
      = food
      %br

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Punk
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield